---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  # Remove MySQL
  - sudo apt-get -f install -o Dpkg::Options::="--force-overwrite"
  - sudo apt-get remove --purge -s mysql\*
  - sudo apt-get autoremove
	- sudo apt-get autoclean

install:
	- pip install ansible
	- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
	- "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
	- "ansible-playbook -i tests/inventory tests/test.yml --connection=local"

# Test role idempotence
  - >
		ansible-playbook -i tests/inventory tests/test.yml --connection=local 
		| grep -q 'changed=0.*failed=0' 
		&& (echo 'Idempotence test: pass' && exit 0) 
		|| (echo 'Idempotence test: fail' && exit 1)
